 #服务端点
server:
  port: 7777

eureka:
  instance:
#    preferIpAddress: true
#    hostname: ${spring.cloud.client.ip-address}
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    ip-address: 120.79.82.72
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
#    租期更新时间间隔（默认30秒）
    leaseRenewalIntervalInSeconds: 10
#    租期到期时间（默认90秒）
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: uaa-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.jdbc.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
#    本地
#    url: jdbc:mysql://localhost:3306/duoboluo?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=true&autoReconnect=true&failOverReadOnly=false
#    服务器
    url: jdbc:mysql://localhost:3306/duoboluo?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT1FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,slf4j
    logSlowSql: true

#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/more_pineapple_purview_uaa?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
#    username: root
#    password: 123456
##    platform: mysql
##    连接池配置
#    type: com.alibaba.druid.pool.DruidDataSource
##    连接池配置
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
##    连接等待超时时间
#    maxWait: 6000
##    配置隔多久进行一次检测(检测可以关闭的空闲连接)
#    timeBetweenEvictionRunsMillis: 60000
##    配置连接在池中的最小生存时间
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
##    打开PSCache，并且指定每个连接上PSCache的大小
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
##    配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: stat,wall,slf4j
##    通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


#无效数据清理：对于json响应接口，我们需要遵守对所有值为null的字段不做返回，对前端不关心的数据不做返回（合理的定义VO是很有必要的）。
#对于spring boot 我们可以用下配置，实现字段值为null时不做返回。
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null


#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#



mybatis:
  configuration:
#  开启驼峰命名转换
    map-underscore-to-camel-case: true
#  开启缓存
    cache-enabled: true
#  实体类路径
  type-aliases-package: com.jnshu.uaaservice.pojo
#  映射文件路径
  mapper-locations: classpath*:mappers/*Mapper.xml

logging:
  config: classpath:logging-config.xml


