eureka:
  client:
    serviceUrl:
      defaultZone: http://120.79.82.72:8761/eureka/
    fetch-registry: true
  instance:
    preferIpAddress: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
server:
  port: 7888

spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /a/
      serviceId: sources-service
    api-b:
      path: /auth/
      serviceId: uaa-service
