---
eureka:
  client:
    serviceUrl:
#      defaultZone: http://120.79.82.72:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    ip-address: 120.79.82.72
#    ip-address: localhost
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
feign:
  hystrix:
    enabled: true
#  url: 120.79.87.72:7777

logging:
  config: "classpath:logging-config.xml"
  level:
    com.jnshu.resourceservice.dao: debug
    com.jnshu.resourceservice: debug
mybatis:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  mapper-locations: "classpath*:mappers/*Mapper.xml"
  type-aliases-package: com.jnshu.resourceservice.pojo
server:
  port: 9090
spring:
  servlet:
    multipart:
#      max-file-size: 20MB
#      max-request-size: 100MB
      enabled: true
      resolve-lazily: false
  application:
    name: sources-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.jdbc.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
#    本地
    url: jdbc:mysql://localhost:3306/duoboluo?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false
#    服务器
#    url: jdbc:mysql://120.79.82.72:3306/duoboluo?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT1FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,slf4j
    logSlowSql: true
    driver-class-name: com.mysql.jdbc.Driver
#  datasource:
#    filters: "stat,wall,slf4j"
#    initialSize: 5
#    logSlowSql: true
#    maxActive: 20
#    maxWait: 60000
#    minEvictableIdleTimeMillis: 300000
#    minIdle: 5
#    password: 123456
#    platform: mysql
#    testOnBorrow: false
#    testOnReturn: false
#    testWhileIdle: true
#    timeBetweenEvictionRunsMillis: 60000
#    type: com.alibaba.druid.pool.DruidDataSource
##    本地数据库
##    url: "jdbc:mysql://localhost:3306/duoboluo?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=true"
##      服务器数据库
#    url: jdbc:mysql://120.79.82.72:3306/duoboluo?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false
#    username: root
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
#    default-property-inclusion: non_null
#    time-zone: Asia/Shanghai
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 0
    password:


#PageHelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true

aliyun:
  sms:
    accessKeyId: LTAIpQdxo8Vu1bwJ
    accessKeySecret: WrO5knbUrHgp14PJ9650hTF45ad19U
    product: Dysmsapi
    domain: dysmsapi.aliyuncs.com
    regionId: cn-hangzhou
    signName: 廿一车
    dateFormat: yyyyMMdd
    endpointName: cn-hangzhou
    templateCode: SMS_142387991
  oss:
    endpoint: http://oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAIpQdxo8Vu1bwJ
    accessKeySecret: WrO5knbUrHgp14PJ9650hTF45ad19U
    bucketName: chedou1
    folder: chedou

multipart:
  enabled: true

#  #location: roy-upload-tmp
#  max-file-size: 100MB
#  max-request-size: 100MB
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 3

